// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJA_jDsJoN5IpzrJTlcXXF_PJk0Jeugg',
    appId: '1:665221207042:web:636ee4f6e02352c0ccc31b',
    messagingSenderId: '665221207042',
    projectId: 'subby-91b88',
    authDomain: 'subby-91b88.firebaseapp.com',
    storageBucket: 'subby-91b88.firebasestorage.app',
    measurementId: 'G-GKHDF8WQR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMw53P0T9lBaACl6AitdT6IjTd8YPR6_8',
    appId: '1:665221207042:android:25162df96b5a34f7ccc31b',
    messagingSenderId: '665221207042',
    projectId: 'subby-91b88',
    storageBucket: 'subby-91b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0sL3XR2ktuNcrCYspF4IIMn9DcM-32NA',
    appId: '1:665221207042:ios:7752d50377b39ea3ccc31b',
    messagingSenderId: '665221207042',
    projectId: 'subby-91b88',
    storageBucket: 'subby-91b88.firebasestorage.app',
    iosBundleId: 'com.bongpal.subby.bongpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0sL3XR2ktuNcrCYspF4IIMn9DcM-32NA',
    appId: '1:665221207042:ios:7752d50377b39ea3ccc31b',
    messagingSenderId: '665221207042',
    projectId: 'subby-91b88',
    storageBucket: 'subby-91b88.firebasestorage.app',
    iosBundleId: 'com.bongpal.subby.bongpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnJA_jDsJoN5IpzrJTlcXXF_PJk0Jeugg',
    appId: '1:665221207042:web:64c89bd96e2b37c1ccc31b',
    messagingSenderId: '665221207042',
    projectId: 'subby-91b88',
    authDomain: 'subby-91b88.firebaseapp.com',
    storageBucket: 'subby-91b88.firebasestorage.app',
    measurementId: 'G-W7HPH35F4M',
  );
}
